[versions]
jacksonDataformatYaml = "2.13.1"
jacksonModuleKotlin = "2.13.1"
jakartaJson = "2.0.1"
julToSlf4j = "1.7.36"
kotlin = "1.9.22"
agp = "8.0.2"
ktor = "2.3.8"
kotlinx-corutines = "1.8.0"
kotlinx-json = "1.6.2"
android-minSdk = "24"
android-compileSdk = "33"
log4jCore = "2.17.1"
logger = "2.0.11"
tyrusServer = "1.17"


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }


[libraries]
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jacksonDataformatYaml" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
jakarta-json = { module = "org.glassfish:jakarta.json", version.ref = "jakartaJson" }
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "julToSlf4j" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-neogation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-corutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-corutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-corutines" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4jCore" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4jCore" }
logger = { module = "org.slf4j:slf4j-simple", version.ref = "logger" }
tyrus-container-grizzly-server = { module = "org.glassfish.tyrus:tyrus-container-grizzly-server", version.ref = "tyrusServer" }
tyrus-server = { module = "org.glassfish.tyrus:tyrus-server", version.ref = "tyrusServer" }